version: "3"
services:
  arttime:
    container_name: arttime
    image: arttime-demo/webapp:latest
    ports:
      - "${port_web}:8080"
      - "${port_web_management}:9990"
    depends_on:
      - keycloak
      - arttimedb
    networks:
      - arttime-public
      - arttime-internal
    
  keycloak:
    container_name: keycloak
    image: arttime-demo/keycloak:latest
    ports:
      - "${port_keycloak}:8080"
      - "${port_keycloak_management}:9990"
    networks:
      - arttime-internal
      - arttime-public

  arttimedb:
    image: arttime-demo/database:latest
    container_name: arttimedb
    restart: always
    environment:
      POSTGRES_DB: arttime
      POSTGRES_USER: arttime
      POSTGRES_PASSWORD: arttime
    #volumes:
    #  - "./database/data/arttime:/var/lib/postgresql/data"
    ports:
      - ${arttime_db_port}:5432
    networks:
      - arttime-internal
      - arttime-public

networks:
  arttime-public:
  arttime-internal:
    internal: true

