version: "3"
services:
  arttime:
    container_name: arttime
    image: arttime-demo/webapp:latest
    environment:
      keycloak_url: "${keycloak_url}"
    ports:
      - "${http_port_web}:8080"
      - "${http_port_web_management}:9990"
      - "${https_port_web}:8443"
      - "${https_port_web_management}:9993"
    depends_on:
      - keycloak
      - arttimedb
    networks:
      - arttime-public
      - arttime-internal
    
  keycloak:
    container_name: keycloak
    image: arttime-demo/keycloak:latest
    ports:
      - "${http_port_keycloak}:8081"
      - "${https_port_keycloak}:8444"
    networks:
      - arttime-internal
      - arttime-public

  arttimedb:
    image: arttime-demo/database:latest
    container_name: arttimedb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - arttime-internal

networks:
  arttime-public:
  arttime-internal:
    internal: true
