version: "3"
services:
  arttime:
    container_name: arttime
    image: artezio/arttime:latest
    ports:
      - "${http_port_web}:8080"
      - "${http_port_web_management}:9990"
      - "${https_port_web}:8443"
      - "${https_port_web_management}:9993"
    depends_on:
      - keycloak
      - arttimedb
    networks:
      - arttime-public
      - arttime-internal
    environment:
      - keycloak_server_url
      - keycloak_client_id
      - keycloak_realm
      - arttime_db_host
      - arttime_db_port
      - arttime_db_name
      - arttime_db_login
      - arttime_db_password

  keycloak:
    container_name: keycloak
    image: artezio/arttime-demo-keycloak:latest
    ports:
      - "${http_port_keycloak}:8081"
      - "${https_port_keycloak}:8444"
      - "9991:9991"
    networks:
      - arttime-internal
      - arttime-public

  arttimedb:
    image: artezio/arttime-demo-database:latest
    container_name: arttimedb
    restart: always
    environment:
      POSTGRES_USER: ${arttime_db_login}
      POSTGRES_PASSWORD: ${arttime_db_password}
    networks:
      - arttime-internal

networks:
  arttime-public:
  arttime-internal:
    internal: true
